### ISSUE TITLE
Sierra Leona 2.29 database metadata issue

### ISSUE THREAD

**Issue by rrowlands** [pgracio/dhis2-docker#25]
I built the 2.29 database image and also the 2.29 web image and booted them with docker-compose up. After the sierra leone dump was loaded into database (on bootup of the database image), the app seems to work just fine, with one exception. When loading the tracker page, I get this error "failed to load metadatata", and the page is half loaded. There are no errors in the container logs, however I did find this error in the javascript console:

```
DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at dhis2.storage.IndexedDBAdapter.value [as setAll] (http://localhost:8085/dhis-web-core-resource/dhis/dhis2-storage-idb-e5bdf19229.js:164:35)
    at dhis2.storage.Store.value [as setAll] (http://localhost:8085/dhis-web-core-resource/dhis/dhis2-storage-04afdd4f4c.js:146:42)
    at http://localhost:8085/dhis-web-tracker-capture/core/tracker-capture.js?_=88ac56894b1f08dced41:636:31
    at mightThrow (http://localhost:8085/dhis-web-core-resource/jquery/3.2.0/dist/jquery.js:3583:29)
    at process (http://localhost:8085/dhis-web-core-resource/jquery/3.2.0/dist/jquery.js:3651:12)
```

This error seems to be isolated to the 2.29 image, since I was able to get 2.26 working just fine using the same workflow.

**Comment by pgracio** [comment]
Hi @rrowlands sorry for the late response. Have you tried to reach to the developers? I don't think this is a problem with the docker images but with the application itself.

**Comment by pgracio** [comment]
I have also published a new docker image for `2.29-sierra-leone` give it a try with that new image.
